# -*- coding: utf-8 -*-
"""Loja de peças motos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X_O5eT9Q1zpSkjFWLnYOFWLpQGdMz3gT
"""

listaPecas = []
#----------- COMEÇO cadastrarPeca ------------#
def cadastrarPeca(codigo):
  print('Você selecionou a opção de CADASTRAR PEÇA')
  nome = input('Por favor, entre com o NOME da peça: {}' .format(codigo))
  fabricante = input('Por favor, entre com o FABRICANTE da peça:')
  valor = input('Por favor, entre com o VALOR (R$) da peça:')
  dicionarioPeca = {'codigo': codigo,
                    'nome': nome,
                    'fabricante': fabricante,
                    'valor': valor}
  listaPecas.append(dicionarioPeca.copy()) #função que acrescenta as peças na lista

#----------- FIM cadastrarPeca ------------#


#----------- COMEÇO consultarPeca ------------#
def consultarPeca():
  while True:
      try:
        print('Você selecionou a opção CONSULTAR PEÇAS')
        opConsultar = int(input('Escolha a opção desejada:\n1- Consultar todas as peças\n2- Consultar peças por código\n3- Consultar peças por fabricante\n4- Retornar'))
        if opConsultar == 1:
          print('Você selecionou a opção CONSULTAR TODOS')
          for peca in listaPecas:
            for key, value in peca.items(): #selecionar cada dicionario da minha lista
              print('{} : {}' .format(key, value)) #selecionar cada conjunto chave : valor do dicionario
        elif opConsultar == 2:
          print('Você selecionou a opção CONSULTAR POR CÓDIGO')  
          entrada = int(input('Digite o CÓDIGO desejado'))
          for peca in listaPecas:
             for key, value in peca.items():
              if(peca['codigo'] == entrada):
                print('{} : {}' .format(key, value))
        elif opConsultar == 3:
          print('Você selecionou a opção CONSULTAR POR FABRICANTE')
          entrada = input('Digite o FABRICANTE desejado')
          for peca in listaPecas:
             for key, value in peca.items():
               if(peca['fabricante'] == entrada): #consulta o dicionario e verifica se o valor inserido é o mesmo cadastrado
                print('{} : {}' .format(key, value))
        elif opConsultar == 4:  
          return
        else:
          print('Código inválido')
          continue   
      except ValueError:
        print('Pare de digitar valores não inteiros') 
#----------- FIM consultarPeca ------------#


#----------- COMEÇO removerPeca ------------#
def removerPeca():
  entrada = int(input('Digite o código da peça que deseja remover'))
  for peca in listaPecas:
      if(peca['codigo'] == entrada):
        listaPecas.remove(peca) 
#----------- FIM removerPeca ------------#


#----------- COMEÇO MAIN ------------#
registrodePeca = 0
while True:
  try:
    print('Bem Vindo ao Controle de Estoque da Bicicletaria da Luana Vieira Machado')
    opcao = int (input('Escolha a opção desejada:\n1- Cadastrar Peças\n2- Consultar Peças\n3- Remover Peças\n4- Sair'))
    if opcao == 1:
      registrodePeca = registrodePeca + 1 #vai acrescentando uma codificação crescente
      cadastrarPeca(registrodePeca) 
    elif opcao == 2:
      consultarPeca()
    elif opcao == 3:
      removerPeca()
    elif opcao == 4:
      print('Obrigado e volte sempre!')
      break 
    else:
      print('Código inválido')
      continue
  except ValueError: 
    print('Pare de digitar valores não inteiros')
  #----------- FIM MAIN ------------#